<?php

namespace Users\UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientsRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientsRequestsRepository extends EntityRepository
{
}
