
kvartiri_control_panel:
    resource: "@KvartiriControlPanelBundle/Resources/config/routing.yml"
    prefix:   /

pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

kvartiri:
    resource: "@KvartiriBundle/Resources/config/routing.yml"
    prefix:   /

users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /

users2:
    resource: "@UsersBundle/Controller/"
    type : annotation
    prefix:   /
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login
 
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login
 
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login
 
facebook_login:
    pattern: /login/check-facebook
 
google_login:
    pattern: /login/check-google

