security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
            FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: kvartiri_control_panel_homepage
            logout:       true
            anonymous:    true



        secure_area:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /login
                failure_path:      /login

                oauth_user_provider:
                    service: my_user_provider
            logout:
                path:   /logout
                target: /
                #success_handler: tracker_user.logout_success_handler
            anonymous:    true

                    # mapping between resource owners (see below) and properties
#                    properties:
#                      facebook: facebookId




#        secure_area:
#            pattern: ^/secure_area
#
#            oauth:
#                failure_path: /secure_area/connect
#                login_path: /secure_area/connect
#                check_path: /secure_area/connect
#                provider: fos_userbundle
#                resource_owners:
#                    github:           "/secure_area/login/check-github"
#                oauth_user_provider:
#                    service: hwi_oauth.user.provider.fosub_bridge
#
#            anonymous:    true
#            logout:
#                path:           /secure_area/logout
#                target:         /secure_area/connect #where to go after logout




#        secured_area:
#              context: user
#              pattern: /.*
#              oauth:
#                resource_owners:
#                  facebook: "/login/check-facebook"
#                login_path: /connect
#                failure_path: /connect
#                oauth_user_provider:
#                  service: users.oauth.user_provider
#              logout: true
#              anonymous: true



        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }


        - { path: ^/secure_area/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secure_area, roles: ROLE_USER }


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN