<?php

namespace Kvartiri\KvartiriBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitiesRepository extends EntityRepository
{
    public function getCities()
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->orderBy('u.name')
        ;
        return $qb->getQuery()->getResult();
    }
}
