<?php

namespace Kvartiri\KvartiriBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Company_HotelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyHotelsRepository extends EntityRepository
{
}
