<?php

namespace Kvartiri\KvartiriBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Hotel_ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Hotel_ServiceRepository extends EntityRepository
{
}
