<?php

namespace Kvartiri\KvartiriBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionsRepository extends EntityRepository
{

}
