<?php

namespace Kvartiri\KvartiriBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoomsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomsRepository extends EntityRepository
{

}
