<?php

namespace Kvartiri\KvartiriBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Room_EquipmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Room_EquipmentRepository extends EntityRepository
{
}
