<?php

namespace Pages\PagesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends EntityRepository
{
    public function byTitles()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u.title')
            ->orderBy('u.id');
        return $qb->getQuery()->getResult();

    }


    public function byTitle($title)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.title = :title')
            ->orderBy('u.id')
            ->setParameter('title', $title);
        return $qb->getQuery()->getResult();

    }

}
